//___FILEHEADER___

import napkin
import SwiftUI
import UIKit

// The launch napkin's listener. Separate `@unchecked Sendable` type
// because the listener protocol is `Sendable` and `UIResponder` is not.
final class ___VARIABLE_productName___AppListener: ___VARIABLE_productName___Listener, @unchecked Sendable {}

// napkin's `LaunchRouter` installs the root view controller into a
// `UIWindow` via `launch(from:)`. Under the SwiftUI App lifecycle there is
// no UIWindow to hand it, so we bridge through a scene delegate supplied
// by a `UIApplicationDelegateAdaptor`. The napkin tree owns the window;
// the `WindowGroup` body is intentionally empty.
@main
struct ___FILEBASENAME___: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) private var appDelegate

    var body: some Scene {
        WindowGroup {
            // The launch napkin's router owns the real UI (installed into
            // the scene's window below). This view is never shown.
            Color.clear
        }
    }
}

final class AppDelegate: NSObject, UIApplicationDelegate {
    func application(
        _ application: UIApplication,
        configurationForConnecting connectingSceneSession: UISceneSession,
        options: UIScene.ConnectionOptions
    ) -> UISceneConfiguration {
        let config = UISceneConfiguration(name: nil, sessionRole: connectingSceneSession.role)
        config.delegateClass = SceneDelegate.self
        return config
    }
}

final class SceneDelegate: UIResponder, UIWindowSceneDelegate {

    var window: UIWindow?
    private var router: ___VARIABLE_productName___Routing?
    private let listener = ___VARIABLE_productName___AppListener()

    func scene(
        _ scene: UIScene,
        willConnectTo session: UISceneSession,
        options connectionOptions: UIScene.ConnectionOptions
    ) {
        guard let windowScene = scene as? UIWindowScene else { return }
        let window = UIWindow(windowScene: windowScene)
        self.window = window

        let listener = self.listener
        Task { @MainActor in
            // `LaunchComponent` is generated by the Launch napkin template;
            // declare and initialize the app's root services there.
            let builder = ___VARIABLE_productName___Builder(dependency: LaunchComponent())
            let router = await builder.build(withListener: listener)
            self.router = router
            await router.launch(from: window)
        }
    }
}
