import os, subprocess, sys, tempfile, unittest

# Deliberately no XML parser here: Python's stdlib XML parsers are unsafe on
# untrusted input (XXE / entity expansion), defusedxml would add a dependency,
# and the sitemap under test is generated by our own script two lines up.
# A structural check is sufficient and dependency-free.

SCRIPT = os.path.join(os.path.dirname(__file__), "..", "gen_sitemap.py")


def make_fixture(root):
    def page(rel, html="<html></html>"):
        d = os.path.join(root, rel)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "index.html"), "w") as f:
            f.write(html)

    page("")                    # landing
    page("about"); page("faq"); page("recipes"); page("changelog"); page("blog")
    page("blog/some-post",
         '<html><head><meta property="article:published_time" content="2026-05-15">'
         "</head></html>")
    page("documentation/napkin"); page("documentation/napkin/presenter")
    page("tutorials/napkin")
    page("when-to-use-napkin")
    page("compare/napkin-vs-ribs",
         '<html><head><meta property="article:published_time" content="2026-07-16">'
         "</head></html>")
    page("main/documentation/napkin")      # versioned copy: must be excluded
    page("2.0.8/documentation/napkin")     # versioned copy: must be excluded
    page("css")                            # asset dir: must be excluded


class TestGenSitemap(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        make_fixture(self.tmp.name)
        out = subprocess.run([sys.executable, SCRIPT, self.tmp.name],
                             capture_output=True, text=True)
        self.assertEqual(out.returncode, 0, out.stderr)
        self.xml = out.stdout

    def test_wellformed(self):
        self.assertTrue(self.xml.startswith('<?xml version="1.0"'))
        self.assertEqual(self.xml.count("<urlset"), 1)
        self.assertTrue(self.xml.rstrip().endswith("</urlset>"))
        self.assertEqual(self.xml.count("<url>"), self.xml.count("</url>"))
        self.assertEqual(self.xml.count("<loc>"), self.xml.count("</loc>"))
        self.assertEqual(self.xml.count("<url>"), self.xml.count("<loc>"))

    def test_static_and_docc_pages_present(self):
        for url in ["https://getnapkin.to/",
                    "https://getnapkin.to/about/",
                    "https://getnapkin.to/blog/some-post/",
                    "https://getnapkin.to/documentation/napkin/presenter/",
                    "https://getnapkin.to/tutorials/napkin/",
                    "https://getnapkin.to/when-to-use-napkin/",
                    "https://getnapkin.to/compare/napkin-vs-ribs/"]:
            self.assertIn(f"<loc>{url}</loc>", self.xml, url)

    def test_versioned_and_assets_excluded(self):
        self.assertNotIn("/main/", self.xml)
        self.assertNotIn("/2.0.8/", self.xml)
        self.assertNotIn("/css/", self.xml)

    def test_blog_lastmod_from_published_time(self):
        self.assertIn("<lastmod>2026-05-15</lastmod>", self.xml)
        self.assertIn("<lastmod>2026-07-16</lastmod>", self.xml)


if __name__ == "__main__":
    unittest.main()
