//___FILEHEADER___

import napkin
import UIKit

// The launch napkin's listener. It's a separate `@unchecked Sendable`
// type — not the SceneDelegate itself — because the listener protocol is
// `Sendable` and `UIResponder` is not. If the launch napkin never needs
// to call back into the app, this stays an empty no-op.
final class ___VARIABLE_productName___AppListener: ___VARIABLE_productName___Listener, @unchecked Sendable {}

final class ___FILEBASENAME___: UIResponder, UIWindowSceneDelegate {

    var window: UIWindow?
    private var router: ___VARIABLE_productName___Routing?
    private let listener = ___VARIABLE_productName___AppListener()

    func scene(
        _ scene: UIScene,
        willConnectTo session: UISceneSession,
        options connectionOptions: UIScene.ConnectionOptions
    ) {
        guard let windowScene = scene as? UIWindowScene else { return }
        let window = UIWindow(windowScene: windowScene)
        self.window = window

        let listener = self.listener
        Task { @MainActor in
            // `LaunchComponent` is generated by the Launch napkin template;
            // declare and initialize the app's root services there.
            let builder = ___VARIABLE_productName___Builder(dependency: LaunchComponent())
            let router = await builder.build(withListener: listener)
            self.router = router
            await router.launch(from: window)
        }
    }
}
